### ISSUE TITLE
프로젝트 흐름 구상

### ISSUE THREAD

**Issue by pennya6** [Capstone-Demo/Capstone-Demo#1]
1. 자연어 처리 모델링
- etri api
- 직접 모델링 -> 최신 트렌드 딥러닝 NLP

2. 웹 구축

3. 자연어 모델과 웹 연결
 - 1) torchserve 모델 서빙후 fast api -> 웹 txt ->curl로 torchserve에 request -> 결과 reponse 
 - 2) 스프링 시스템 콜 -> serviceImpl, 아규먼트 받아서 내용 로드
 - 3) flask -> spring과 flask 연동 
 ( Spring 서버에서 Flask 서버로 파일을 전송하면 Flask 서버에서 해당 파일을 받아 파이썬 코드로 원하는대로 처리해주고, 다시 Spring 서버로 돌아오는 식으로 진행이 가능한 것이다. https://kimcoder.tistory.com/254 )

- 만약 힘들다고 하면 open cv 방법(텍스트 추출)

**Comment by pennya6** [comment]
https://taetaetae.github.io/2018/06/29/simple-web-server-flask-apache/

**Comment by pennya6** [comment]
자바에서 파이썬 모델 사용 방법
https://joytk.tistory.com/3

flask spring server data request
https://yanoo.tistory.com/14

**Comment by pennya6** [comment]
고려해야할 점   
자연어 처리 모델 구축시  우리가 구현할 기능은 어떤게 될것 인지?
예시 )  음성인식, 내용 요약, 번역, 사용자의 감성 분석, 텍스트 분류 작업(스팸 메일 분류, 기사 카테고리 분류), 질의 응답 시스템,

**Comment by HongJungWan** [comment]
핵심 기능

1.  Java Jsoup 웹 크롤링 -> 각종 최신 영문 뉴스를 수집 -> 유저에게 단어 제공
2. [공공 AI 오픈 API*DATA](https://aiopen.etri.re.kr/service_list.php) -> 음성인식

<br>

<img src="https://user-images.githubusercontent.com/76596316/147330544-9809ea55-96d2-4881-8118-61695f0bb2dc.png" width="40%" height="30%"></img>

**Comment by HongJungWan** [comment]
1. 모델 구축은 되도록 피한다
2. 음성인식 (발음평가 API)
