### ISSUE TITLE
예제를 통해 얻은 것과 추가로 해야 될 것

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#10]
요약 : NDK 및 Android openCV를 사용할 수 있는 개발 환경을 설정했다.

<br/>

추가로 해야 될 것
Tesseract OCR 사용하기

**Comment by HongJungWan** [comment]
주제 : 딥러닝 영상분류 / 영상인식 

논의 : 모델 뭐 사용할지

<br/>

---

딥러닝 영상분류/영상인식 입문,     

강의자료는 홈페이지 가입해서 받으면 된다.
[홈페이지 링크](https://tacademy.skplanet.com/live/player/onlineLectureDetail.action?seq=159)


<br/>

[무료 강의 링크](https://www.youtube.com/watch?v=gIa5Ztp5ViE&list=PL9mhQYIlKEhe5tqXV2KAeR0H-_tbn8esv)
	        
                  <러닝 타임 약 3시간>

		1강 - 딥러닝 개요 및 동작방식 이해
		2강 - 영상 데이터 이해
		3강 - 실습 환경 준비 & 실습데이터
		4강 - VGG16을 사용한 영상분류 이해 및 실습
		5강 - ResNet을 사용한 영상분류 이해 및 실습
		6강 - 영상인식 이해
		7강 - YOLO를 사용한 영상인식 이해 및 실습
		8강 - SSD를 사용한 영상인식 이해 및 실습

**Comment by khg339** [comment]
기존 OCR을 문자 인식에 사용할 것인가?
아니면 문자 인식까지 구축하고 기존 OCR과 비교?

**Comment by HongJungWan** [comment]
숙제 : Tesseract OCR -> YOLO 모델 사용한 번호판 오픈소스 및 자료 찾기
