### ISSUE TITLE
숙제

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#12]
1. Tesseract OCR -> YOLO 모델 사용한 번호판 오픈소스 및 자료 찾기
2. 제목, 팀명 -> 회의까지 최소 1개씩 생각해오기.

**Comment by HongJungWan** [comment]
## 숙제

1-1. [YOLO, OCR](https://github.com/poten-jay/object-detection/tree/55243f0239f48eec6065e4ac7b77635505ff7294)

개념 정리용

<br/>

1-2. [딥러닝 기반 열악 자동차 번호 이미지 복원 및 인식 기술](https://github.com/msmn1729/capstone_final)

뽑아 쓰기용


👆 위에 두 개는 안드로이드 사용 안 함

<br/>

---

2. 

제목 :  1-2 살짝 바꾸면 될 듯

팀명 :  No-Coder

**Comment by pennya6** [comment]
1. 안드로이드 문자인식 단계 정리 사이트
https://yeolco.tistory.com/67

2. 우리가 잘 생각해야할점
- 저번에 딥러닝 모델을 구축안하기로 한것이 아닌지?
- 딥러닝 모델 구축 0 -> yolo 사용
- 딥러닝 모델 구축 X -> tesseract ocr, opencv만 사용

3. 현재 우리가 test code삼아 사용하던 코드는 tesseract ocr 사용 코드 -> 즉 딥러닝 모델 구축 X
-> 따라서 딥러닝이라는 표현이 아닌 "영상처리를 통한 한신대학교 주차관리페이지"이런식으로 들어가야할듯

4. 텐서플로우 라이트 ocr api 사용
-> 구현된 CRNN 모델 사용이니 그래도 안쓰는것보다는 좋을듯 -> <strong>OCR API를 찾아보자</strong>
https://www.tensorflow.org/lite/examples/optical_character_recognition/overview

5. 저번에 test한 code 진행항
- 카메라가 죽는 문제 발생으로 인해 두개의 예제 코드 합치는 중, 시간이 좀더 걸릴듯 하지만 이외의 기능들 다 구현완료

6. 팀명 : open cv를 쓰니까 비슷하게 open hanshin?

7. 계획  : 장기로 가니까 서비스 배포까지 가는게 맞는거 같다. -> 참고할만한 자료가 있을지?
+ 안드로이드 앱 구축 (ocr tesseract service + DB) (2명) 
+ 웹페이지 구축(1명)

**Comment by khg339** [comment]
1. 올리신거 봤는데, 모델 구축 안하고 OpenCV, tesseract ocr로 가는 게 맞는 것 같아요

2. 제목 : 영상처리 및 문자 인식 기반 한신대학교 주차 관리 페이지
영상처리 -> OpenCV, 문자인식 -> OCR

3. 팀명 : 라이선스
자동차 관련 간단한 이름 생각해봤어요

**Comment by HongJungWan** [comment]
1. 컴퓨터 비전 및 머신러닝 기반 차량 관리 서비스 -> 대학교
2. OpenCV 및 OCR Tesseract 기반 차량 관리 서비스 ★ -> 대학교 
3. 영상처리 및 문자 인식 기반 차량 관리 서비스 -> 대학교

안드로이드 앱 구축 (ocr tesseract service + DB) (2명) - 시연, 현지
(웹페이지 구축) 및 서비스 배포(1명) - 정완 

팀명 : Re-Coder

1학기 문서 작업 계획 : 답이 안 보이면 모인다.

다음 회의 

숙제 : 역할 별 진행 사항, (화요일 오후 1시)
회의 : 화요일 수업 끝나고 일정

**Comment by pennya6** [comment]
[현지, 시연 회의]
1. ocr api 고려, 모델까지, 정확도 
2. 동영상 vs 사진 -> 텍스트 추출
3. 동영상처리 ocr api
