### ISSUE TITLE
아이디어 구상

### ISSUE THREAD

**Issue by pennya6** [Capstone-Demo/Capstone-Demo#15]
# OpenCV 및 OCR Tesseract기반 차량 관리 서비스 
->Tesseract 삭제 필요 또한 API사용시 OpenCV도 빼는게 맞다고 판단, 제목 수정 필요
  

### 아이디어 구상
1. 문제점 : 대학교 차량관리 시스템의 불편, 불필요한 부서, 경비실 방문 등 -> 코로나 19로 비대면 서비스 확대의 필요성 언급 가능할 듯
2. 사용자 및 타겟층 : 전국의 대학교 -> 큰 틀은 동일하되 각 대학별 서비스 운영을 가능하게 설계할 필요있음 
3. 대충정리한 사항들
![image](https://user-images.githubusercontent.com/53909511/158158038-ba468621-96be-4ae9-a7b8-07ae2053c9b0.png)

**Comment by khg339** [comment]
그럼 대학 별로 서비스를 다르게 만들 수 있도록 생각하자는 건가요?
ㄴ 구현해야 하는 부분들이 너무 많아지는 것은 아닌지..


제목은 저번에 나왔던 후보 중에서 "영상 처리 및 문자 인식을 통한 주차 관리 서비스" 이런 식으로 가는 것 어떤가요

**Comment by pennya6** [comment]
1. 대학별로 별도의 서비스 구현이라기 보다는 큰틀내 대학성 특성을 살릴수 있는 느낌? 그런식으로 생각했습니다.
2. 제목은  "영상 처리 및 문자 인식을 통한 주차 관리 서비스" 너무 좋아요!

**Comment by HongJungWan** [comment]
유저는 위에 서비스,  관리자는 아래 서비스?

**Comment by HongJungWan** [comment]
[우리 주제 완성본](http://www.ezled.co.kr/page/sub4_3_3_2)

위 링크에서 우리 주제로 이미 만듬, 요구사항 참고하면 될듯

**Comment by pennya6** [comment]
[교수님 피드백]
1. 차별성
2. 딥러닝 Open API가 많아서 사용하는건지? 왜 이걸 선택한건지 정확한 설명 필요
