### ISSUE TITLE
1차 피드백

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#17]
1. 기존의 서비스와 차별화된 점이 무엇인가?

2. 주제가 흔하다. (1번에서 한 번 더 물어본 질문, 프로젝트 목적 재확인)

3. 개인이 관리할 수 있도록 만들 목적인가? (목표 고객층이 어디냐?)

**Comment by HongJungWan** [comment]
[팀원 피드백](https://github.com/Capstone-Demo/Capstone-Demo/issues/15#issuecomment-1067587668)

**Comment by khg339** [comment]
1. 주제
저는 교수님께서 기존의 서비스라던지 주제에 대해 언급하신 이유가 **저희의 주제 선정 동기가 제대로 전달되지 않아서** 라고 느꼈어요. 그래서 "단순히 머신 러닝을 사용하기 위해 선정한 주제인가요?" 같은 질문을 받은 것 같아요.

2. API
이것도 1번과 이어지게 되는 이야기 같습니다.
**주제를 정한 목적이 정확하지 않은 상태에서** "모델 구축은 어려워서 API" 라고 이야기 드렸던 점이 교수님께서 의문을 가지게 되신 것 같아요

급하게 준비해서 짧게 했던 발표라 저희가 제대로 정리가 안됐던 것 같아요

그래서 저는 지난 시간에 지적 받았던 부분들은 이번 발표 때 저희가 왜 이 주제를 택했는지, 정확하게 설명하고 넘어가면 충분할 것 같아요.

**Comment by khg339** [comment]
발표 순서 구상해봤는데 추가되어야 할 부분이나 빼고 싶은 부분 피드백 남겨주세요.

1. 한신대학교 주차권 발급 과정(문제점 언급)

![454545](https://user-images.githubusercontent.com/87069221/159112602-f478b33d-83aa-4bdf-a25a-f1045c2f8ef7.PNG)
- 대학원교학팀 방문, 경비실 제출 등 대면으로 처리해야 하는 과정이 포함됨
- 서류를 직접 관리하고 등록시킴


**-> 비대면으로 등록 및 관리가 가능한 편리한 서비스가 필요하다고 느낌**

----------------------------------
2. 우리 프로그램 사용자는 누가 될 것인가?
- 등록자 측면, 관리자 측면 정리해서 언급

-------------------------------------
3. 프로그램에 어떤 내용을 담을 것인가?
**안드로이드** -> 번호판 인식 카메라 역할
**DB** -> 차량 번호 및 출입 시간 저장
**웹** -> 기록 확인, 요금 처리

--------------------------------
4. 기대되는 효과는 어떤 것인가?
여기는 자료 조사 해서 넣으면 될 것 같아요
번호판 인식으로 바꾸면 어떻게 편하게 될지

**Comment by khg339** [comment]
그리고 혹시 주제에 "한신 대학교"나  여러 대학에 접목 시킬 것이라면 "대학교" 키워드를 넣는 것은 어떻게 생각하세요?

**Comment by HongJungWan** [comment]
발표 순서랑 구상 다 좋구 , **Lean Canvas** 작성해서 마지막에 보여주면 보는 사람이 이해 쉬울듯, 일요일에 같이 만들자

**Comment by pennya6** [comment]
[의견]
1.  모든 대학에서 사용가능한 시스템이라는 점에서 한신대학교 주차권 발급과정의 문제뿐만 아니라 <strong>다른 타 대학의 문제점도 언급하는게 좋다고 판단</strong> -> <strong>즉 여러 사례들을 보여주고 따라서 이런 문제점들을 해결할 수 있는 총괄 시스템을 제시한다.</strong>
2. 기존의 서비스에서 <strong>비대면 관리 서비스의 확장</strong>의 원인을 적절하게 제시하여 기존의 서비스 확장 느낌을 강조하는것도 좋을듯
3.  교수님이 지적하신 부분중에 딥러닝이라는 표현을 저희가 처음에 주제로 이야기를 해서 딥러닝 -> 오픈 API -> 주차장 이런식으로 주제가 선정되었다고 생각하시는것 같은데 저희한테 좋은 점은 아니라고 생각합니다. 이번 발표에서 기존부터 주제를 고려하였고 그러던 중 주차장 관리 서비스에 문제점을 개선할 필요가 있었다 따라서 우리는 이런 서비스를 제공하여 문제점을 해결하고자 한다 라는 부분을 강력어필해야한다고 생각합니다.
+ 딥러닝 -> API -> 주차장 (교수님 지적)
+ 주차장서비스문제 -> 해결 -> 확장된서비스제공 -> 딥러닝 API을 활용한 다양한 서비스 제공 (아니다 이런식으로 로직이 이루어졌다)

4. 오픈 API전에 안드로이드로 저희가 시도한 test code로 정확도 확인시 <strong>정확도가 낮은 문제점으로 인해 오픈 API를 사용</strong>하게 되었다라는것도 이야기해야할 것 같습니다.
5. 안드로이드에 다른 서비스들을 넣는 부분도 고려는 해야 할 필요는 분명함
6. 주제에 <strong>대학교 키워드를 넣을 필요가 있어 보임</strong>
7. 이번에는 발표시 시각자료를 분명하게 준비하여 보다 정확하게 우리의 주제를 전달하면 좋을듯
8. 현지가 써준 피드백 기대효과 부분에 번호판인식으로 바꾸면 어떻게 편할지 -> 지금도 아마 학교에서 사용하는 프로그램은 번호판인식 시스템일것, <strong>따라서 기존의 시스템의 개선과 전반적인 온라인 서비스 제공 등등 확장된 서비스임을 어필할 필요가 있음</strong>

**Comment by HongJungWan** [comment]
깔끔하구만

---

 1. 확신 x
 * 즉 여러 사례들을 보여주고 (여기까지 가능) 
 * 총괄 시스템을 제시 (구현 어떻게 함)

3. 가능
4. 가능 
5. 가능
6. 1번과 동일
7. 가능 (Lean Canvas)
