### ISSUE TITLE
웹 담당 전달사항 (고정) 🐣🐣🐣🐣🐣

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#18]
1. 일요일 오후 7시, 프로젝트 목적 및 차별성에 관한 회의 진행

* 업무 공유 & 회의합시다
* Lean Canvas 작성

---

<br/>

2. 주차 관리 시스템 SpringBoot, JPA로 intelliJ에서 구현된 2020~2022년 자료 찾을 수 있다면 링크 올려주세요,

저는 맛 간 프로젝트 밖에 못 찾았습니다. 😔😔😔😔😔😔😔

---

3. 우리랑 주제 비슷하다고 생각합니다, 보고 평가해주세요.

[참고 자료](https://github.com/4rangKim/FinalProject)

링크 들어가면 유튜브 링크 있으니 봅시다.

**Comment by HongJungWan** [comment]
굵은 글씨 _선호_

* Mybatis(SQL Mapper 종류) vs **JPA(ORM 기술)**
* **intellij(서비스)** vs eclipse(국비)
* **Maven** vs **Gradle**
* **application.properties** vs **application.yml**
* VO vs **DTO**
* JSP vs **Thymeleaf**

하나씩 섞인 프로젝트 비교하면 머리 깨질 거 같아요. 🤯

**Comment by HongJungWan** [comment]
## Admin 측 기능 

* 차량등록
  * 차량에 대한 기본 정보 입력 (이름, 차량번호 ...)
  * 예약 가능 날짜, 예약 가능 시간, 일일 최대 예약 가능 인원, 시간당 최대 예약 가능 인원

* 등록된 차량 목록 (조회)
  * 차량 삭제

* 등록된 차량 상세 페이지 (조회, 수정)
  * 등록된 차량 정보 수정

* 출입차 현황 조회
  * 날짜별, 시간별 예약 현황 확인
  * 잔여 자리 현황 확인  

<br/>

---

## Client 측 기능 

* 본인인증 ( Oauth2 - Naver, Kakao, Google)

* 예약
  * 자리 선택 -> 예약 날짜 선택 -> 예약시간선택 
  
* 예약확인

* 결제 
  * 이거 로직 고민 좀 해봐야 할 듯

**Comment by HongJungWan** [comment]
![ERD_스샷](https://user-images.githubusercontent.com/76596316/159121062-bb2f6963-625e-41c4-9380-57c020faf7fa.png)

<br/><br/>

* 한 명의 USER는 한 개의 예약석(RESERVE_ITEM)을 가진다.

* 한 개의 예약석(RESERVE_ITEM)은 한 개의 주차장(PARKING)을 가진다.

* 한 명의 관리자(ADMIN)은 여러 주차장(PARKING)을 가진다.

* 한 개의 주차장은 여러 예약 가능 날짜(AVAILABLE_DATE)를 가진다.

* 한 개의 예약 가능 날짜(AVAILABLE_DATE)는 여러 예약 가능 시간(AVAILABLE_TIME)을 가진다.

* 한 개의 주차장은 여러 차량(Car)을 가진다. (여러 종류의 차량)

**Comment by HongJungWan** [comment]
application.yml 로그인 오류 잡았고, mysql 이론상 연결은 되는데 런타임 도중에 admin 정보 안 들어가짐
h2로 테스트하던가, 데이터 직접 노가다로 만들어주던가, DB에 들은 게 없으니 조회 시 오류 나는 듯

**Comment by pennya6** [comment]
[웹 질문]
1. 예약시스템에 대한 의문

**Comment by HongJungWan** [comment]
> [웹 질문]
> 
> 1. 예약 시스템에 대한 의문

<br/>

저기서 예약은 자리 예약(선택) 말하는 거임

<br/>

1. 차량 등록이랑 별도 기능
2. 주차장 내 공간은 한정되어 있으니까 예약(선택) 해서 주차해야지

**Comment by HongJungWan** [comment]
[이거 코드같이 분해할 사람 구함](https://github.com/Jarvis1542/capston)

이것보다 쓸만한 거 못 찾음 일주일 동안
