### ISSUE TITLE
캡스톤 3주차 발표

### ISSUE THREAD

**Issue by khg339** [Capstone-Demo/Capstone-Demo#19]
[캡스톤 발표1.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8314454/1.pdf)

발표자료 완성했습니다
피드백 남겨주시면 밤에 수정할게요~

**Comment by pennya6** [comment]
너무 좋아요😘

**Comment by HongJungWan** [comment]
깔끔하다 좋네

**Comment by khg339** [comment]
[교수님 피드백]
1. 확실한 차별성이나 특징들을 계속 물어보셨다(다른 팀에도 다 마찬 가지일 듯)
2. 결론이 나오게 된 과정을 아주 자세하게 설명해주실 원하신다(tesseract 정확도 그래프 원하심)

**Comment by pennya6** [comment]
[의견]
1. 차별성 부분
+ 모든 대학이 사용가능한 서비스
+ 앱 서비스의 추가기능 -> 이후에는 안드로이드 기능이 카메라 인식으로 넘어가면 이 기능이 필요없어짐, 따라서 웹에 추가적인 차별성 서비스가 없다면 안드로이드에서의 기능을 들어가는게 필요하다고 생각
2. tesseract 정확도는 만들어오겠습니당

**Comment by HongJungWan** [comment]
[공지]

목요일까지 각자 숙제 생각해옵시다.
