### ISSUE TITLE
개인 숙제

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#20]
1. (공통) 차별점 1개씩 생각해오기 (기능 or 구현 or 서비스 로직)

<br/><br/>

2. (개인) 숙제 1개
- oauth2 로그인 페이지 구현하기 (구글, 네이버, 카카오톡), 뷰 템플릿 손보기
- 완료하면 branch에 올림

**Comment by HongJungWan** [comment]
일요일 오후 7시까지

**Comment by pennya6** [comment]
[숙제]
1. 안드로이드 관리자 기능 추가?..., 정기차량 이외의 방문차량의 경우에 사전무인정산기가 없다보니까 웹에서 결제하던지, 안드로이드에 추가적으로 결제할 수 있는 시스템? 
2. 주차장을 학교에서 제휴로 관리해서 가입하는 느낌?... 그러면 제휴인 모든 학교의 주차장을 사용할수 있음....
3. 안드로이드 CameraX API 써서 카메라 기본 완성
+START : 카메라 시작
+STOP : 카메라 끝
+RECOGNITION : 번호판 촬영 후 preview 보여주기, 추후에 인식메소드 연결할 계획
+레이아웃은 저번에 올린 5번 레이아웃에서 일부 변경
![image](https://user-images.githubusercontent.com/53909511/159946764-5b8a7696-8d99-4a7d-a5ae-ee5b3ed33fa5.png)

[안드로이드 진행사항]
siyeon/main : 안드로이드 CameraX API적용 완료 Base app 구축완료
siyeon/working : ML kit 적용 진행중

**Comment by khg339** [comment]
개인 숙제는 시연이랑 같은 거 해보기로 해서 지난 피드백 받은 거에 대해서 자세히 조사해봤습니다.

**1. 변경될 것이라고 이야기가 나오고 있는 T 주차**
![image](https://user-images.githubusercontent.com/87069221/160265976-28ffd01a-3948-4b44-a84e-37e78d54f0cc.png)

- 서비스 내용 
 : 카카오 T 맵에 카드, 차량 번호 등록 -> 주변 주차장 탐색 -> 주차 요금 정보 띄움 -> 예약(결제) -> 주차장 사용

- 우리 서비스와 비교
 : 관리자 측면은 자세히 기제 되어 있지 않지만, 카카오인데.. 당연히 관리가 더 잘될 것임
  kakaoT for manager >> https://tcp.kakaomobility.com/tenant
 : 사용자 측면은 '앱'과 '웹'의 차이일 뿐 비슷한 내용
 : 결제 방식이 정기권보다는 시간제로 외부인들도 쉽게 사용할 수 있도록 되어있음


---------------------------------------------------
**2. 우리와 같은 서비스가 분명히 존재할 텐데?**

하이그린파킹 >>   https://www.ajpark.co.kr/service/master 

- 서비스 내용
 : 매출 데이터 제공, 정확한 입/출 차 데이터 제공, 주차장 이용 차량 관리, 장비 원격 제어, 할인 시스템

- 우리 서비스와 비교
 : 거의 동일하다고 볼 정도로 매우 유사
 : 다른 점을 찾자면 '웹' 이 아닌 '앱' 을 통한 서비스


---------------------------------------------------------
**3. 우리들만의 차별성은 어디서 찾을 수 있을까?**

-> T주차에서 주변 주차장 탐색 후 예약하여 결제가 되는 시스템을 사용
-> 학교 내부의 구조까지 고려된 시스템일까? (단순히 '한신대학교 주차장' 이라고 기재되어 사용되지 않을까')
-> 60주년 기념관과 채플실, 한울관 등 건물에 따라 상당한 거리가 있음
-> **T주차에서 모티브를 얻어서 학교 내의 주차장을 구역 별로 나누어 예약할 수 있으면 어떨까**
-> 외부인도 사용하기 편하고, 무엇보다 우리 학교 학생들과 직원들에게 특화된 서비스가 되지 않을까 생각되었다.


-------------------------------------------------------
**4. 정리**

- 서비스 내용 : 기존과 동일 + 주차장 구역을 나누어 등록할 수 있도록 함
- 주장할 수 있는 차별성
 1) 관리자와 사용자의 웹을 통한 소통
 2) 특정 대학교에 맞춤화된 서비스 제공

**Comment by pennya6** [comment]
1. 그러면 T주차처럼 주차구역 예약도 가능하게 하는 걸까요?
-> 정기권 등록하면서 주차구역 예약 시스템도 좋은것 같아요

**Comment by HongJungWan** [comment]
[현지 의견 + 전기차 충전소 혼합한 캡스톤 자료](https://github.com/Jarvis1542/capston)

👇

[스토리보드.pptx](https://github.com/Capstone-Demo/Capstone-Demo/files/8357119/2._.pptx)

<br/>

이건 DB, Oracle
Mysql 이랑 Oracle은 SQL구문부터 다 다른 걸로 알고 있음

개발할거면 erd script 작성해야 됨. 👉 아니면 코드 다까봐서 직접 짜보던가 불가능할 것 같음

위에꺼 만들어도 설계가 Orcale 쓴다고 생각하고 JPA 썼을건데 잘 써먹을 수 있을지 모르겠음

<br/><br/>

들어가서 전기차 충전 주차장 관련 부분 제거하고 봐도 개발 규모 큼.

패키지 분류 몇개 이상하게 되어있음

<br/><br/>

결론 

1. 2020년 이후로 스프링 부트를 사용한 parking-system 프로젝트는 거의 없다. (대부분 C#, 이클립스 IDE 기반 엄청 오래된 소스)
2. 있으면 백엔드 스킬만 사용한 RESTful API, (2016~2018년도 작성된) 
3. 괜찮아 보이면 중국인이다.
4. 그나마 비즈니스 로직 분석해서 써먹을 만한게 내가 올린 링크다.
5. 근데 저것도 개발 규모가 크고 마음대로 프로젝트 관리해서 써먹으려면 분석할 인력이 필요하다.
6. 만만한 줄 알았는데 직접 하나하나 까보니 블루오션이다. 
7. 안드로이드와 웹의 기능을 좀 더 명확하게 나눠서 생각해 보자.
