### ISSUE TITLE
안드로이드, 웹 역할 구분

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#21]
안드로이드👉  User 타겟

차량 등록
주차권 신청
요금 납부
주차장 구역 예약

<br/>

---

일단 💭 변동 있음 ※※※※※※ 그냥 적은거

<br/>

웹 👉 Admin 타겟

사용자 관리
*  유저 상태 페이지(/user)

<br/>

주차장 검색 
* 유저 주차장 페이지(/serach)

<br/>

주차장 상세 정보
* 유저 주차장 상세 페이지(/search/{lot_no})

<br/>

출입 관리
* 어드민 주차장 정보(/admin_search)
* 어드민 주차장 상제 페이지(/master_search/{lot_no})
<br/>

확인 부탁

**Comment by khg339** [comment]
네 페이지 하나하나 말고 기능만 두고 보면 맞는 것 같아욤!

출입 관리 부분은 전 사용자가 언제 들어왔고 나갔는지가 기록된다고 생각했고, 사용자 관리는 정기권을 주고 구입한 회원들을 관리한다고 생각했습니다

그리고 주차장 정보랑 검색은 하나로 묶어서 생각해도 될 것 같아요
