### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by khg339** [Capstone-Demo/Capstone-Demo#22]
**첫번째 ERD** - 테이블, 개체, 속성 이름은 확정되면 작성하도록 할게요

일단 관리자는 아이디랑 비밀번호만 들어갈 것 같아서 제외했습니다
관계 오류나 추가되어야 할 부분 있으면 피드백 주세요

![스크린샷(80)](https://user-images.githubusercontent.com/87069221/160400275-16ae86f8-f60a-4b24-aece-87dfc2629c20.png)

**Comment by HongJungWan** [comment]
확인

**Comment by khg339** [comment]
- 한 사람 당 차량은 1개만 등록할 수 있다
- 비회원의 경우를 고려하여 회원 코드를 자동으로 자동으로 부여한다.
- 회원의 경우에만 개인정보가 필요로 하고, 비회원은 회원 코드와 차량 등록만 필요하다.
- 정기권, 시간제 모두 요금제 테이블 안에 포함한다

**Comment by pennya6** [comment]
출입에 주차장번호가 필요할듯

**Comment by khg339** [comment]
여러 대학교에 적용될 수 있도록 변경 -> 위의 사용자-차량 개체와의 모든 관계를 아래 이미지로 수정

![image](https://user-images.githubusercontent.com/87069221/160615087-c5ef219f-d641-4571-b94e-5323cb08726f.png)

**Comment by HongJungWan** [comment]
## 현재 웹 구성 DB
 
<br/>

![ERD_스샷](https://user-images.githubusercontent.com/76596316/160755551-0c44c416-a5d8-4f2c-9077-ec722d30aac7.png)

<br/><br/>

Type, Null 값, Default 명시된 값 필요하면 말하셈

<br/>

위 스크린샷 기준으로 로컬 정상 동작함

<br/>

---

<br/>

[WEB] 1차 데모 마감 기한 4,17일

* 이때 팀원 1차 데모함
* 피드백 받고 추가적인 기능이나 View 수정함
* 최초로 기획한 요구사항은 이때까지 끝내려고 함 웹은
* 이후 DB 공유(맡기고) 및 AWS 클라우드 건들려볼 생각 (애초에 DB가 서버에 계속 띄워져 있어야 공유가 될 것 같아서)
