### ISSUE TITLE
개인 숙제 (3.30~4.4), 작성 바람

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#23]
## 개인 숙제

1. WEB 만들기 시작함 (아래 내용 참고)
2. 프로젝트 계획 견적 내기 

<br/><br/>

[WEB] 1차 데모 마감 기한 4,17일

이때 팀원 1차 데모함
피드백 받고 추가적인 기능이나 View 수정함
최초로 기획한 요구사항은 이때까지 끝내려고 함 웹은
이후 DB 공유(맡기고) 및 AWS 클라우드 건들려볼 생각 (애초에 DB가 서버에 계속 띄워져 있어야 공유가 될 것 같아서)

---

<br/>

## 다음 회의

4.3일 오후 5시

**Comment by khg339** [comment]
### **개인숙제**

------------------------------

**1. DB 완성**

[주차관리DB.zip](https://github.com/Capstone-Demo/Capstone-Demo/files/8392437/DB.zip)

  압축 파일에 ERD 따로 첨부했으니까 번거로우시면 ERD만 먼저 봐주세요!
  정완 오빠가 준 백신 예약 기반인데 추가된 부분은 **car, purchase, charge** 테이블이라 이것들 위주로 확인 부탁 드려요
  큰 수정 사항 없으면 일단 진행하고 세부적으로 바뀌는 부분들은 나중에 수정해도 될 것 같습니다.

-------------------------------

**2. 사용자 앱 로그인 구현 시작**

  안드로이드에서 mysql 직접 접근 불가 -> WAMP 다운로드 후 PHP도 사용
  
  일단 user table만 만들어서 진행
  
![user_talbe](https://user-images.githubusercontent.com/87069221/161415572-ab3595b7-1b5e-4560-8e46-d5dda6152afb.PNG)

  MariaDB라고 되어있는데, mysql이 인수되어서 바뀐거라 mysql이랑 동일

**Comment by pennya6** [comment]
[개인숙제]
1. ML kit 구현 완료 
-> 한글 정확도가 생각보다 낮음... ㅠ
-> Kakao API 시작해보겠습니다.....
-> MLkit 한글 정확도 높일 수 있는 방법을 찾음 시도예정
![image](https://user-images.githubusercontent.com/53909511/160890913-40bab96b-5eaa-4e29-bc1a-b92196697764.png)
![image](https://user-images.githubusercontent.com/53909511/160890927-bbbfb0b3-4be9-4bf6-9380-cfd8be723463.png)
![image](https://user-images.githubusercontent.com/53909511/160890946-f4ce2395-5973-49fe-88f2-547dba0087f3.png)

2. ocr 결과가 다이얼로그에 나오게 수정
영어 감지 결과는 정확도 높음
![image](https://user-images.githubusercontent.com/53909511/160977239-c94029a2-f599-4f20-90ef-65173f8194ce.png)

3. 한국어 성공
![image](https://user-images.githubusercontent.com/53909511/161391231-782bb97e-bef9-4597-997f-52cfd9c86d0b.png)
![image](https://user-images.githubusercontent.com/53909511/161391235-6ebbd1b2-8a10-487b-9c82-e6089e854f76.png)
-> 실제 차량으로는 시도를 안해봄... 회의전에 할 예정

4. 차량 입차, 출차 시간을 위해 사진 찍는 시간 불러오기 추가
