### ISSUE TITLE
발표준비 

### ISSUE THREAD

**Issue by pennya6** [Capstone-Demo/Capstone-Demo#26]
1. 근거자료 필수
2. 목적이 잘 들어나게 작성, 그리고 보다 자세하게, 대표적인 기능들도 잘 들어나게 할것
3. 관련연구는 어떤것들이 장점이고 단점이다. 따라서 우리는 이런 단점들을 보완할 수 있다. 이런식으로
4. 개발환경은 4번항목에 적어주기, 정확하게 작성, 그림으로 표현, 프로세스들이 잘 보이게 만들기
5. 일정계획도 보다 자세하게 , 팀원들의 기여도까지 작성
6. 글보다는 그림
7. 필요성강조 목적도 명확하게
8. 기능도 보다 이미지를 통해 디테일하게 보여드릴것
9. 만약 문제점을 보여드릴거면 사용자후기를 가져오면 좋을듯

**Comment by pennya6** [comment]
[발표목차]
1. 관련 연구
+ 선일일렉콤 주차 관리 운영 시스템(Web) -> CNN 모델 사용
+ ML Kit 정확도 관련 논문
![image](https://user-images.githubusercontent.com/53909511/162133794-3575aa1b-6bcc-4b8e-ba85-28be50c8a7be.png)
https://www.koreascience.or.kr/article/JAKO202109835990879.pdf

2. 문제 및 목적
+ 문제점 : 기존에 존재하는 주차관리서비스는 사용자가 직접 방문하여 신규가입, 수정해야하는 문제점이 있다. 또한 다양한 주차관리서비스들은 서로 독립적으로 운영되고 있다. (ex) 사전결제기능, 신규가입, 예약서비스 등등)
<Strong>기존의 다양한 서비스들의 독립적인 구조의 이미지 추가 예정</Strong>

+ 개발목적 : 비대면 차량관리 서비스 제공 
<Strong>우리 서비스의 연속적인 흐름의 서비스 구조 이미지 추가 예정</Strong>

+ 차별성 언급 :  보통 회원제로 정기권가입자 대상의 서비스 제공, 하지만 일반인 방문자에게도 사전결제 서비스를 제공함으로써 앱 사용자 범위를 확대하려고 하였다.
관리자에게 앱서비스? 혹은 사용자에게 ocr 관련 서비스?(다른 서브 기능들 고민해야할 듯)

3. 주요기능 및 기대효과
+ 주요기능 (타겟층에 대한 언급, 간단한 UI를 첨부하여 서비스 로직도 첨부할 예정)
 3-1) Web Server 기능 - Admin
 3-2) App Server 기능 - User(정기권사용자 & 방문자)

+ 기대효과 (차별성에 대해서 재언급)


4. 개발환경
+ 개발환경 : 
깃허브, 인텔리제이, 안드로이드스튜디오

5. 위험요소(부족한점 및 문제점)
+ 위험요소 : 

6. 일정계획 및 팀원별 기여도

7. 참고문헌

**Comment by HongJungWan** [comment]
Web Server 기능 - Admin

**Comment by pennya6** [comment]
[발표자료 ppt]
[캡스톤발표.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8459382/default.pdf)
[캡스톤발표.pptx](https://github.com/Capstone-Demo/Capstone-Demo/files/8459383/default.pptx)

**Comment by HongJungWan** [comment]
## 웹 개발환경

프레임 워크 : Spring boot 2.6.x

IDE : IntelliJ (Community Edition 2021.1.2)

ORM : JPA (Hibername, Spring Data JPA)

DBMS : MySQL

템플릿 엔진 : Thymeleaf

* Spring Dependencies(활용하는 라이브러리)
  *  Spring Web
  *  Spring Data JPA
  *  Spring Security
  *  Lombok
  *  ModelMapper

<br/> 사용하는 라이브러리까지 적는 건 좀 그런가?

---

## 인프라 구축

Amazon EC2
Amazon RDS

👆 방학 때 하면 졸작 끝,
