### ISSUE TITLE
DB 최종 수정 및 건의 ＆ 제안서 초안 ＆ 회의 순서

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#29]
## 4.17일 오후5시

<br/>

* 1. 변경사항 부분을 올려주세요.

<br/>

* 2. DB 테이블의 역할과 속성의 목적에 대해 적어주세요.

<br/>

* 3. 회의날에 통합 설계 및 조정합시다.

**Comment by HongJungWan** [comment]
[0413_DB_명세서_WEB 기준_홍정완.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8475705/0413_DB_._WEB._.pdf)

<br/>

위의 pdf 파일 참고 바랍니다.

WEB 동작 기준 작성

**Comment by HongJungWan** [comment]
* DB 최대한 변경 안 하려고 노력해서 생각한점 인지하고 있습니다. 
* 추가적인 수정 및 변경사항 전부 다 작성해 주세요.

**Comment by HongJungWan** [comment]
[캡스톤디자인_제안서_Re_Coder_4.16 초안.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8499913/_._Re_Coder_4.16.pdf)

---

제안서 초안을 작성했습니다.

담고 싶은 내용 및 추가적인 수정이 필요한 부분은 텍스트 형태로 전달해 주세요.

**Comment by HongJungWan** [comment]
일요일 오후5시 회의 순서

<br/>

* 1. 제안서 초안 검토 (25분)

* 2. DB 변경 사항 회의 (45분)

**Comment by khg339** [comment]
제안서 수정 및 추가하고 싶은 부분

[제안서_4.17_수정제안.txt](https://github.com/Capstone-Demo/Capstone-Demo/files/8500320/default.txt)

**Comment by khg339** [comment]
DB회의 자료

[0417_DB회의자료.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8501052/0417_DB.pdf)

**Comment by pennya6** [comment]
1. 캡스톤제안서 수정사항
+ 문제점추가 -> 독립적인 주차서비스
+ OCR 용어 -> ML Firebase OCR 용어 수정
+ 가. 관련연구 
시력 취약계층을 위한 신용 카드 번호 인식 연구 tess-two 관련 정확도 실제 구현 사진 첨부하여 실제 진행사항 첨부
+ 표1 이라는 표현이 없음 -> 그림 및 표에 대한 타이틀 부여 필수, 또한 표1에 대한 본 논문 칸이 Re-coder 주차 서비스보다 크기 때문에 수정이 필요해보임, 본논문이 더 강조되는것 처럼 보임
+ 관련연구에 선일일렉콤과의 차별성 부분이 들어가야한다고 판단
+ 나. 서비스 개발 모델 
<strong>이 프로젝트는 구현해야 하는 기능 구현을 단계별로 나누고 우선순위를 설정한 후, 우선한
단계가 끝날 시에 다음 단계를 진행하는 방식으로 진행하며, “반복/점증 모델[2]”을 일부
참조한다. 다만, 한정된 시간으로 인해 요구 분석 및 설계는 프로젝트 시작 시에 결정하며, 프로젝트 진행 중에는 해당 결정사항을 최소한으로 수정하는 것을 목표로 한다. </strong>
이 부분 수정 필요해 보임 
-> 본 프로젝트 구현시 단계별로 나누고 우선순위를 정한다. 이후 우선한 순위가 끝나면 다음 단계로 진행되며 "반복/점증 모델"을 일부 참조한다. 단, 요구분석 및 설계는 프로젝트 구현 시작 시 결정하며, 진행 중에는 수정을 최소화함을 목표로 한다.
+ 가. OpenCV
현재 OpenCV 사용 안함
+다. Firebase ML kit 추가
Ml Kit Text Recognition v2 API는 중국어, 일본어, 한국어 및 라틴 문자 집합의 텍스트를 인식할 수 있다. 
+주요 기능별 프로세스 추가 필요
+ 개발환경 beta -> v 수정

2. DB 건의사항
+ 웹 관련 table : 이미 구현이 진행되고 있는 상태이며 구현이 되고 있는 것으로 보아 테이블에 대한 이해만 맞추고 넘어가면 된다고 생각, 따로 수정이 불필요
+ 안드 Table : 구현 진행 안된 상태이며 웹쪽 구현에 문제가 없다면 purchase, charge table 수정 필요, 즐겨찾기 테이블 신규 생성 필요

**Comment by pennya6** [comment]
[DB해석.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8501125/DB.pdf)

**Comment by HongJungWan** [comment]
ERD -> 4.26 마감
제안서 -> 4.18 마감

PPT -> 제안서 받고, 23일에 작성해서 24일 공유하기(최종 피드백).

**Comment by pennya6** [comment]
[수정본]
[캡스톤디자인_제안서_Re_Coder_수정본.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8505416/_._Re_Coder_.pdf)

**Comment by khg339** [comment]
[수정본]
[수정DB.zip](https://github.com/Capstone-Demo/Capstone-Demo/files/8556683/DB.zip)

**Comment by pennya6** [comment]
2022.04.26
1. 안드 학교 하나 기준으로 구현
2. 대학 db 풀네임으로 
3. 현지 - 안드 db 쪽 완료해서 올려주기로 함
4. 정처기 실기 끝나고 코딩 시작하기로 함
5. 웹 db 그냥 받아서 안드에서 사용, 즉 웹쪽에서 아무거나 다 하셔도 됩니다...
6. 주차구역 -> 장애인, 전기차 등 으로 바뀜

**Comment by pennya6** [comment]
[2022.04.26 발표 피드백]
1. 공격 -> 전체적인 문제? , 보안적인 문제는 어디에나 존재한다.
2. 학생들이 할때 발생할 수 있는 문제점들을 좀더 고려해야 한다.
3. 기능을 좀더 집중적으로 설명했으면 좋겠다. 
4. 차량인식 문제점에 좀더 focusing 되어 있었음, 주차관리에 좀더 초점을 맞추면 좋을 듯 하다.
