### ISSUE TITLE
요구사항분석

### ISSUE THREAD

**Issue by khg339** [Capstone-Demo/Capstone-Demo#30]
[2022.04.26 포함 되어야 할 내용]
- 기능에 대한 아주 세부적인 설명 -> 구체적인 프로세스 명시
ex) 로그인 페이지
     -> 로그인 시 어떤 내용이 필요한가
     -> 로그인 시 어떤 방식으로 입력이 필요한가
     -> 로그인 완료 시 어떤 페이지로 넘어가는가

**Comment by HongJungWan** [comment]
5,1일 오후 5시 회의

**Comment by pennya6** [comment]
[2022.04.28]
1. 기능명세서
2. UX flow
3. 요구사항명세서
위의 자료들 준비하면 좋을 듯 합니다.

**Comment by khg339** [comment]
발표자료
[Re-coder_요구사항분석_발표자료.pptx](https://github.com/Capstone-Demo/Capstone-Demo/files/8599707/Re-coder_._.pptx)

- 애니메이션이 적용되어 있어서 ppt로 업로드
- 명세서 부분은 앞에서 언급되지 않은 부분 위주로 간략하게 진행할 예정
- 교수님께 발표자료 보내겠습니다.

**Comment by pennya6** [comment]
[교수님 피드백]
1. 비기능은 자료에 미첨부, 제안서에만 첨부
2. 기능에 대한 부분 잘 정의, 각 요구사항도 id로 정리
3. 프로세스 잘 정리함
4. 흐름이 앞에서 요구사항 id 그런것들과 매칭하면 좋을듯
5. id가 붙은것들은 개발을 다 하기 어려울수 있음 그러면 아이디로 관리하게 된다  굳굳 
6. 다만 데베쪽 모델링이 안되어있는게 아쉽다 추가하길 희망
