### ISSUE TITLE
5.1까지 개인 숙제

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#31]
1. 기능명세서
2. UX flow
3. 요구사항명세서

<br/>

처음에는 Web, Android 따로 작성,
일요일 회의 때 합치기,
Web은 일요일전에 초안 작성해서 올려드림

**Comment by HongJungWan** [comment]
<br/>

[web-admin-요구사항명세서.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8592653/web-admin-.pdf)

<br/>

---

<br/>

![Admin-Web-User Flow](https://user-images.githubusercontent.com/76596316/165995493-96c9c713-7a01-4fa7-8e46-fe51375e08d1.png)

<br/>

---

<br/>

![IA](https://user-images.githubusercontent.com/76596316/165995500-e4937cf8-4eb2-4bd4-9bfe-f1696c6459fb.png)

**Comment by khg339** [comment]
[안드로이드_기능명세서.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8597797/default.pdf)

[안드로이드_uxflow.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8597800/uxflow.pdf)
