### ISSUE TITLE
5.3 & 5.10 요구사항_자료

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#33]
[요구사항명세서_5_10_Web_발표용_팀별.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8686356/_5_10_Web_._.pdf)

* 05_10 교수님 연구실에서 발표한 pdf

---

[Re-coder_요구사항_0503.ppt.zip](https://github.com/Capstone-Demo/Capstone-Demo/files/8686373/Re-coder_._0503.ppt.zip)

* 05_03 요구사항 발표자료

**Comment by khg339** [comment]
[Re-coder_요구사항명세.pdf](https://github.com/Capstone-Demo/Capstone-Demo/files/8688785/Re-coder_.pdf)

0503 제출 자료 (안드로이드 포함)

**Comment by khg339** [comment]
![image](https://user-images.githubusercontent.com/87069221/168313042-d70d60b2-389c-4503-a448-0ec12ca5e2c0.png)

[교수님께서 수정 원하신 부분]
- purchase, entry, departure 연관 관계
  -> entry, departure 테이블 없애고 purchase의 속성으로 사용하는 것으로 수정

**Comment by HongJungWan** [comment]
> ![image](https://user-images.githubusercontent.com/87069221/168313042-d70d60b2-389c-4503-a448-0ec12ca5e2c0.png)
> 
> [교수님께서 수정 원하신 부분]
> 
> * purchase, entry, departure 연관 관계
>   -> entry, departure 테이블 없애고 purchase의 속성으로 사용하는 것으로 수정

ㅇㅋ

**Comment by khg339** [comment]
![image](https://user-images.githubusercontent.com/87069221/168461164-2a0c401b-2902-45b6-a6b4-267bff662c08.png)
