### ISSUE TITLE
회의록

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#4]
# 회의 진행

<br>

**웹 플랫폼에 AI 기술 넣어보자! 👉 공모전 수상작에 사용된 기술을 참고해 플랫폼을 만들자! 👉 아이디어 접근이다, 망하기 좋은 접근이다.**

<br>

팀원 a의 피드백

2. 문제에 초점하지 않았다.
3. 새로운 가치를 제공하지 않는다.

팀원 b의 피드백

3. 유저의 불편함에서 접근하지 않았다.
4. 기능이 우선이 아니다.

<br>

---

### 근거

지그재그, 카카오톡 등의 플랫폼도 초기 서비스 출시는 MVP(Minimum Viable Product) 관점으로 접근했다.

4단계 진행 방식, 문제 인식 👉 가설 👉 근거 👉 검증 단계를 거치고 빠르게 서비스 출시.

<br>

주제부터 잡자 👉 문제 인식부터 하자🔎

<br>

---

### 우리의 목표는 무엇인가? 

1. 각자가 원하는 기술을 넣어서 프로젝트를 진행한다.
2. 문제 인식 👉 가설 👉 근거 👉 검증 단계를 거치고 주제를 찾는다. (최대한 간단하게) 🚩
3. 기존에 있는 플랫폼에서 살짝 방향을 튼다. 

<br>

---

<br>

* 팀원 a가 제시한 의견을 고려한 내용 👇

<br>

## 팀원 c의 생각 👉 (유저의 불편함)
 
졸업 작품을 하는데 주제 찾기가 힘들다 👉

국내 논문에 비해 영어 논문은 짧은 시간 내에 읽기 어렵다. **(문제)** 👉

핵심 내용을 1줄 요약해준다면 보다 직관적이고 시간이 절약된다. **(가설)** 👉 

"긴 논문들의 경우 ‘tl;dr’이라고 표시해 걸러내기도 한다. ‘tl;dr’는 (Too long, didn't read)’의 줄임말로 흔히 "글이 너무 장황하고 읽기 힘드니까 좀 간결하게 써봐라"라는 비난의 뉘앙스다."  **(검증에 대한 근거)** [기사 링크](http://www.aitimes.com/news/articleView.html?idxno=134274) 👉

<br><br>

**다른 논문 요약 사이트와 차별점**
* 영어 논문 요약에 초점을 맞춘 사이트는 대부분 해외사이트
* 국내 사이트의 경우 요약 기능이 부가적으로 들어가있거나 직관적이지 않다.

<br>

### 결론
* 직관적인 영어 논문 요약 플랫폼 모델을 제시한다.

---

<br>

**Comment by HongJungWan** [comment]
자유로운 팀 분위기에 맞춰 회의록 양식은 편하게 맞췄습니다. 
다 읽고 의견 달아주세요. 😀

**Comment by pennya6** [comment]
논문요약 아이디어 좋은거 같습니다!!
추후 가능하다면 영어에만 초점을 두는 것이 아니라 한글도 같이 사용가능 한지 확인까지 하면 좋을 것 같습니다.
영한번역은 API를 쓸 예정이니 그리 문제는 되지 않을 것 같다는 생각입니다.

**Comment by pennya6** [comment]
참고자료

https://aihub.or.kr/sites/default/files/2020-12/5_18.%E1%84%8B%E1%85%AD%E1%84%8B%E1%85%A3%E1%86%A8%E1%84%83%E1%85%A6%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A5_%E1%84%82%E1%85%A9%E1%86%AB%E1%84%86%E1%85%AE%E1%86%AB%E1%84%8C%E1%85%A1%E1%84%85%E1%85%AD%E1%84%8B%E1%85%AD%E1%84%8B%E1%85%A3%E1%86%A8%E1%84%83%E1%85%A6%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A5.pdf

**Comment by pennya6** [comment]
한국교육학술정보원_해외학술지 논문 API
http://www.riss.kr/apicenter/apiSearchDissEtc.do#redirect

**Comment by pennya6** [comment]
2.14 질문
1. 주제를 공통적으로 가는가? NLP를 하고싶은건지?
2. 일년장기가 가능한다고 한다면 기본의 주제로 가는건지? -> 학기별로 끊어서 연장된 프로젝트를 가능하게 할 수도 있다고 들음
3. 혼자 NLP 처리를 해야하는건지? 정확한 역할 분담 원함
4. 정확한 설계구조는 추후에 정리하면 될것 같은데 구현가능성도 따져야할듯 -> 몇가지 아이디어를 잡고 구현가능성과 기술스킬들을 정리하자
5. 프로트엔드는 혹시?…

**Comment by pennya6** [comment]
[주제 아이디어]
일단 모델 구축이 들어가면 힘들어질것이다...
그러면 api로 계속 돌리는 방법밖에 없는데...

1. ocr -> 번역 api 
2. 점자번역프로그램 (모델 구축 필요) https://hidden-loca.tistory.com/8?category=909779
3. 수화인식프로그램 (모델 구축 필요) 어려울수 있다.... 열공필요
4. 안드로이드로 자동차 번호판인식 -> 시간 데이터베이스 저장 -> 웹페이지로 선 결제 시스템 구축 https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=beodeulpiri&logNo=221610049429

**Comment by HongJungWan** [comment]
점자번역프로그램 -> ex) https://jumjaro.org/

**Comment by HongJungWan** [comment]
[주제 아이디어]
음성 인식 (STT) : 다양한 플랫폼과 서비스들에 상용화되어 있다.

시각 장애인을 위한 음성 인식(STT) 서비스

자세한 내용 2.18 19:00 회의

**Comment by khg339** [comment]
[주제 아이디어]

**1.	대학교 스터디 그룹원 찾기**
대학생들이 비대면으로 학교도 잘 못다니는 현대 시대 반영,
같은 대학이라는 범주에서 다른 유사 웹보다 안정성을 느낌
-	대학생 회원가입
(대학교, 나이, 사는곳, 희망 분야, 대표 해시태그, 해당 분야에 대한 본인 실력)
이때, 학생증을 찍어 해당 대학 인증을 넣고싶은데, api 못찾음
-	그룹원 찾기(대면 유무, 나이대 설정, 희망 분야, 원하는 실력대 입력) 
DB에 저장된 인물 찾기
-	채팅 기능 구현(스프링으로 구현할 때 웹 소켓을 이용하는 것 같음)

**2.	영상 속 좋아하는 유명 인물 찾기**
네이버 api 중 유명인과 유사도를 추출하는 api가 있음
내가 찾고자하는 인물 입력
-> 해당 인물이 출연하는 영상들 제공
-> 영상을 클릭하면 해당인물이 언제 나오는지 제공(예를들어 00:58:49 이런식으로)

이때, 위의 유명인 유사도 api만 사용하는 게 아니라
영상 트래킹이라는 알고리즘을 따로 구현해야 하는 것 같음
아직 자세히 조사가 안돼서 정확히는 모르지만 공부가 안되어 있는 만큼
매우 어려울 것으로 예상..

**3.	메뉴 추천(메뉴가 아니더라도 다양하게 적용 가능할 듯)**
혼자있을 때, 또는 여러 사람들과 함께일 때 여러 이유로 메뉴 선택에 어려움

-	다양한 음식이미지 보여줌 -> 즉각적으로 표정 분석(감정인식 api사용)
-	표정 분석을 기반으로 메뉴 추천(혼자 or 다수 모두 구현)
-	음식점 추천


**4.	여행가이드**
국내든 해외든 여행지에 가면 긴 줄글의 설명들을 자주 볼 수 있음
->	이를 촬영하여 업로드(OCR API를 사용하여 글 불러오기)
->	내용을 해석하고, 중요 내용 요약
->	이와 유사한 다른 장소 추천

**Comment by HongJungWan** [comment]
1. 

점자 번역관련 -> 웹 서비스

주요 고객층 :  시각 장애인 법정 대리인이나 보호자 및 점자 학습자
                       시각 장애인을 위한 플랫폼을 제공하는 기업 or 담당자


2. 

자동차 번호판인식 (영상처리) -> 시간 데이터베이스 저장 -> 웹페이지로 선 결제 시스템 구축

주요 고객층 : 우리 학교 학생 or 교직원

문제 -> 해결방안 -> 수익성
