### ISSUE TITLE
0529 진행사항

### ISSUE THREAD

**Issue by khg339** [Capstone-Demo/Capstone-Demo#45]
<이번 주 개별 진행 사항>

1. 정보 조회 팝업 띄우기

2. 정기 권 구매 정보 DB 삽입
   - 남은 기한이 오늘까지 인 경우 or 정기 권이 없는 경우에만 구매 처리
   - 정기권을 이미 보유하고 있을 때 마이페이지 확인 요청 Toast
   
3. 예약 Spinner 값 DB연동
   - college에서 enabled=Y, date_accept>0인 목록 띄움
   - colleg 선택 후, college_id에 따라 
    enabled=Y, quantity>0인 parking_area 목록 띄움

------------------------------------------------------------------------------------

=> 이제 3분기 시작하면 될 듯

**Comment by pennya6** [comment]
https://github.com/Capstone-Demo/Capstone-Demo/issues/14#issuecomment-1138189333
