### ISSUE TITLE
주제 (후보)

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#5]
### 22.02.20일 오후 7시까지

여기다가 정리합시다. 링크+

**Comment by khg339** [comment]
**no.1 점자 번역 프로그램 구현 예시**
우리와 비슷한 이유로 시각장애인의 정보 제공자들을 위한 점자 번역 프로그램
https://hidden-loca.tistory.com/7
(모델 생성과 구현 과정이 자세히 기술됨)

**no.2 점자로**
한글 -> 점자 이지만, 참고 사항이 많을 것으로 예상
점자로  https://jumjaro.org/
구현 깃허브 https://github.com/teamdotsix/jumjaro

**no.3 숙명 여대  학사 졸업프로젝트**
https://github.com/Youngmi-Park/check-dot
1번과 같은 맥락으로 구현된 프로젝트
잘못 기입된 점자를 신고할 수 있는 방안으로 발전시킴

**Comment by HongJungWan** [comment]
목표 : 기술적인 포인트를 잘 갖고 와서 퍼포먼스를 낼 수 있는가?

핵심 기능 위주로 개발(구현) -> 기술적 포인트 (최신 기술)

<br/>

### 회의 때 나온 [키오스크 + 시각장애인 주제]

Blind-Kiosk(시각 장애인 주문 어플) - 공공데이터 활용 BI 공모전
https://github.com/sumeen99/blindkiosk


----------------------------------------------------------------------

<br/>

나중 이야기 ~
커스텀 아이디어 -> 티맵이 귀로 들림 -> 안내견 대체 느낌

현지가 찾은 자료 외 나머지 전부 학습 or ocr 관련 자료.

**Comment by HongJungWan** [comment]
안드로이드 (클라이언트)
스트링 부트 (서버)
AWS - MongoDB (DB)

다른 공모전이랑 다르게 설계도 없어서 하나하나 까봐야 함.
그래도 다른 오픈소스 비해서 코드 잘 정리된 듯.

**Comment by pennya6** [comment]
[자동차 번호판 인식을 통한 주차요금 정산 웹페이지]
1. 주차요금 정산 관련 코드는 코테에서 많이 다루고 있음
https://velog.io/@qodlstjd12/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-Kakao-%EC%A3%BC%EC%B0%A8-%EC%9A%94%EA%B8%88-%EA%B3%84%EC%82%B0-Java

2. 관점은 차령번호 인식을 영상처리로 구축하는 부분
인프런 차량번호판 인식 프로젝트 - https://www.inflearn.com/course/tensorflow-%EC%8B%A4%EC%A0%84%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EC%98%AC%EC%9D%B8%EC%9B%90

Tesseract 이용한 자동차 번호판 인식기-
https://maxtime1004.tistory.com/38?category=971805

감지모델은 논문이나 최신 트렌드 참고해서 사용하는것이 좋을 듯


3. 비슷한 사례
주차장 관리지기앱 - opencv, tesseract ocr을 이용한 안드로이드 주차장 관리앱
가게앞 또는 자투리 땅을 주차장으로 이용하고자 할때 앱을 통하 입차처리하여 요금 계산 시스템
https://m.blog.naver.com/PostView.naver?blogId=beodeulpiri&logNo=221719960335&proxyReferer=https:%2F%2Fm.blog.naver.com%2FPostView.naver%3FblogId%3Dbeodeulpiri%26logNo%3D222045064295%26proxyReferer%3Dhttps:%252F%252Fwww.google.com%252F

+ 추가적으로 비슷하게 택시 번호판조회와 같은 기능으로도 구현가능할듯

**Comment by HongJungWan** [comment]
## 회의 목표 : 주제 선정 마무리

### 회의 시간 : 30분

</br>

회의 진행 : 

1. 개인 리뷰 각 2분, (총 6분)
2. 의견 공유, 10분
2. 투표, 2분
3. 향후 일정 조정, 10분

**Comment by HongJungWan** [comment]
결정 : [번호판 인식을 통한 [???] 웹페이지]

1. 관련 자료 찾기 (다음 회의까지 해오기.)


2. 개발과정


3. 개발기간
1학기 : 
2학기 :


3. 역할
