### ISSUE TITLE
[WEB] 단속 내역 ui, 기본 로직

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#50]
<img src="https://user-images.githubusercontent.com/76596316/174951193-bae0493b-e11d-45dd-a4e0-f6a6d571b222.png" width="600">

<br/><br/>

안드로이드 앱에서 데이터 값 넣어줘야 함.

1. 차량번호 (모바일 관리자가 입력)
2. 단속 사유 (리스트로 선택)
3. 단속 날짜 (예시로 올린 해당 포맷에 맞춰 타입 선정)
4. 처리 결과 (처리 대기 중 -> 완료, 모바일 관리자가 버튼 클릭 시 내용 변경)

<br/><br/>

확인 후, 피드백

**Comment by khg339** [comment]
주차장에 예약석은 따로 지정해 둔다고 가정하고 생각하면 될까요?
없으면 어떤 차량이 예약 위반인지 알 수 없을 것 같아서요

예를 들어서 
A라는 사람이 만우관 주차장 예약
B,C,D는 그냥 만우관 주차장이 비어있으니까 주차를 함
A가 주차하려는 데 자리가 없음
B,C,D 중 누가 예약 침범?

**Comment by HongJungWan** [comment]
3개다 예약 위반

현장 관리자가 각각 3번의 단속 및 입력 필요

아마 지속적으로 계속 감시하기보단, 음주집중단속 기간 처럼 진행하면 좋을듯

**Comment by pennya6** [comment]
1. 음주집중단속 기간처럼 주기적으로 단속하는 기간이 존재하고
2. 위와 같이 예약신고로 확인 요청이 들어오면 추가적으로 단속
이런식으로 저는 이해했습니다.

**Comment by pennya6** [comment]
[DB]
데이터베이스 생성시 추가적으로 주차장 ID값이 필요할 것 같아요

**Comment by HongJungWan** [comment]
> 1. 음주집중단속 기간처럼 주기적으로 단속하는 기간이 존재하고
> 2. 위와 같이 예약신고로 확인 요청이 들어오면 추가적으로 단속
>    이런식으로 저는 이해했습니다.

확인
