### ISSUE TITLE
6.26 회의록

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#51]
## 1. 단속 로직 마무리

1-1. 유저들이 신고 -> [web]에서 신고 내역 보고, (app 관리자 호출(DB, 알림(FCM, AWS 알림))) -> [app 관리자] 출동

[안드로이드 모바일 앱에서 Amazon Pinpoint 푸시 알림 수신하기](https://aws.amazon.com/ko/blogs/korea/how-to-receive-push-notification-from-amazon-pinpoint-from-mobile-applications/)

* email이나 문자 sms 에다가 알림 보내는 건 쉬울 거 같은데, 이것도 aws 홈페이지 안에서 동작시키는 것
* 우리가 원하는 건 웹 관리자 페이지에서 액션 줘서 -> 모바일 관리자 화면에서 알림을 확인하는 것인데, 이걸로 구현한 거 있나 찾아보는 중  
* [AWS SNS (Simple Notification Service) 메시지 보내고 받기](https://ltlkodae.tistory.com/28)
* 대부분의 예제들은 위에처럼 간단한 예제들 , 더 찾아봐야 할 듯

<br/>

[HTTP/S 엔드포인트로 팬아웃](https://docs.aws.amazon.com/ko_kr/sns/latest/dg/sns-http-https-endpoint-as-subscriber.html)

* 이 방법으로 하면,  aws https 인증서 발급부터 받아야할듯 
* 대충 스윽 보니까 이렇게 하는 방법밖에 없을듯

<br/>

* 웹에서 웹에 알림 보내기, 모바일에서 모바일에 알림 보내기는되는데, 웹 애플리케이션에서 모바일 애플리케이션에 어떻게 알림 보내냐 

* ~~카카오 알림 api 건들여보기~~
  * ~~모바일은 카카오 로그인 구현 x -> 그럼 알림톡 사용 불가능~~

<br/>

1-2. rol -> crop ( 0 )

<br/><br/>

**Comment by HongJungWan** [comment]
6.28~6.29 찾아보고 알려드림,

요구사항 명세서
DB 고려 ->

7.3(일) 일요일 DB 계획 최종 결정

**Comment by HongJungWan** [comment]
* Web 관리자 -> Web 유저 or App 관리자 -> App 유저면 편할 텐데

* 우리는 Web 관리자 -> App 관리자 알림 호출 
  * 이렇게 구현한 AWS SNS 자료가 찾기 어려움.

<br/>

# web 관리자 -> app 관리자, 알림 기능 

### 1. aws sns로 구현할 경우 

<br/>

web 관리자 페이지에서 액션 👉

구독자(app 관리자)에게 sms(문자) 👉

구독자(app 관리자)가 문자 확인 후 👉

해당 App 실행해서 신고 내역 확인

<br/>

* 결과 : 최초에 원하는 요구사항이랑 거리가 좀 있고, 이렇게 만들려고 해도 고생 좀 해야 됨
* 이렇게 만들면, 그냥 관리자가 근로장학생한테 직접 문자 보내는 거랑 뭔 차이 있냐고 물어볼 듯

<br/><br/>

### 2. FCM을 통해 push 알림 보내기

<br/>

* 클라이언트(안드로이드) 설정
* 서버단(SpringBoot) 설정 

<br/>

Spring -> Firebase -> App 

[[SpringBoot] FCM을 통해 Push 알림 보내보기](https://sol-devlog.tistory.com/11)
[[SpirngBoot] FCM Push 서버 구축](https://galid1.tistory.com/740)

*  Firebase 관련된 부분은 나보다 더 잘 알 것 같아서 구현 가능성 물어보려고 올려봄.

<br/><br/>

### 3. 웹소켓으로 안드로이드 앱에 푸시 메시지 전달

<br/>

* 그냥 이거 말고 FCM 쓰라는 의견들이 다수

**Comment by pennya6** [comment]
1. 1번은 너무 복잡하고 오빠가 언급한 문제점 공감합니다.
2. FCM 사용하면 저희 클라우드 2개 쓰는거 아닌지?...

**Comment by HongJungWan** [comment]
> 1. 1번은 너무 복잡하고 오빠가 언급한 문제점 공감합니다.
> 2. FCM 사용하면 저희 클라우드 2개 쓰는거 아닌지?...

응 2개 쓰는거지,
근데 알림 보내는거 대부분 fcm 쓰는듯
일단 https 트러블 슈팅 잡고, 더 찾아보게
