### ISSUE TITLE
7.3 회의록 -> Github issue 회의

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#53]
[fcm 서버1](https://sol-devlog.tistory.com/11)

* 1차 테스트 시도 (7,5) -> 성공
* [서버 어떻게 구현했는지 간략하게 정리함 보고 싶으면 보셈](https://velog.io/@daydream/Spring-FCM%EC%9D%84-%ED%86%B5%ED%95%B4-Push-%EC%95%8C%EB%A6%BC-%EC%84%9C%EB%B2%84-%EA%B5%AC%EC%B6%95)

<br/>

* 결론

![FCM Postman](https://user-images.githubusercontent.com/76596316/177419793-88570710-ec80-4302-a232-eef9fd6db2d8.png)

<br/>

<img src="https://user-images.githubusercontent.com/76596316/177419814-5630e3c2-d4b0-453f-88ef-e76e8ae41451.png" width="250">

<br/>

---

<br/>

2. DB 테이블 현지가 만든거 검토해서 올리고 

<br/>

![erd](https://user-images.githubusercontent.com/87069221/177032273-9a303cf0-5e3c-4a6e-a294-645fbf7294af.PNG)

CREATE TABLE reports (
reports_id bigint not null AUTO_INCREMENT,
user_id bigint not null,
college_id bigint not null,
car_number varchar(255) not null,
cause varchar(255) not null,
report_date varchar(255) not null,
reprot_result varchar(255) not null,
constraint reports_PK primary key(reports_id),
FOREIGN KEY (user_id) REFERENCES user (user_id),
FOREIGN KEY (college_id) REFERENCES college (college_id)
);

<br/>

---

<br/>

3. 개발

**Comment by HongJungWan** [comment]
### 수정 요구사항

* JPA 안 쓰고 상속 전략 쓸 수 있나? -> 괜히 이렇게 했다가 안드에서 데이터 넣을 때 안될까 봐
* 되면 이렇게 하고
* 안되면 테이블명이랑, 신고 결과 Enum 클래스로만 하는 걸로

<br/><br/>

## 수정한 테이블

![수정한 테이블](https://user-images.githubusercontent.com/76596316/177101364-41b985ca-af44-49a9-95df-ead6b678f950.png)

* 뒤에 2 붙은거는 신경쓰지 마셈

<br/><br/>

## 테이블명은 단수

* 단수로 네이밍 하는 것을 권장하니까

<br/><br/>

## report_date ->BaseTimeEntity 추상 클래스 만들어서 Report 테이블에 상속받을 경우

### 이유

* 슈퍼-서브타입 (Extended E-R)
* 정규화된 데이터
* 데이터의 중복이 없음
* 예약, 결제, 신고한 시간 관리할 때 편함 -> 나중에 수정할 때 

![BaseTimeEntity](https://user-images.githubusercontent.com/76596316/177101540-8324bfc5-9ead-46a0-b879-7f01c0bf364b.png)

<br/><br/>

![Report](https://user-images.githubusercontent.com/76596316/177101581-816389ab-68d7-4d34-9a34-8f291f664ca0.png)

<br/><br/>

## DateTime 사용하는 이유 

* DATETIME 타입은 날짜, 시간 모두 포함할 때 사용하는 타입
* 2022-07-04 16:13:30 이런 식으로 포맷 제공해 줘서 최초 요구사항이랑 맞음


<br/><br/>

## 신고 결과는 Enum 클래스로

![status](https://user-images.githubusercontent.com/76596316/177101656-2cebacda-c87a-4c86-adb4-e1534b1327d0.png)

* 지금까지 해왔던 것처럼

**Comment by HongJungWan** [comment]
# 7.8일 회의 주제 

<br/>

# 전달 사항

* 시연 
  *  현지가 짠 DB 검토, (위 게시글 참고)
  
  *  내가 올린 수정 DB 검토 -> 3개 중에 2개만 될듯함. 근데 봐보긴 하셈, (위 게시글 참고)
  
  *  DB 수정하고 싶거나 추가적인 아이디어 있으면 이슈에 올리기

<br/><br/>

* 현지 
  *  내가 올린 수정 DB 검토 -> 3개 중에 2개만 될듯함. 근데 봐보긴 하셈, (위 게시글 참고)
  
  *  DB 수정하고 싶거나 추가적인 아이디어 있으면 이슈에 올리기 
  
  *  DB 팀원 확인 다 끝나면 DB 수정본 이슈에 올리기

<br/><br/>

* 정완
  * Web View -> Server (Rest API) -> Firebase Server -> Android Device  
  
  * Web View에서 Server 요청 건들이게 구현한 자료 찾아보기
  
  * 있으면 demo 버전으로 개발해 보기
    *  7.13일까지 여러 시도 좀 해보려고 함.

<br/><br/>

# etc.

* 하고 싶은 거나 개발 미리 하고 싶으면 알아서 하고 issue에 올려주셈 확인함 그럼
* 전달사항도 있으면 issue 올려주셈

**Comment by khg339** [comment]
**테이블 명 수정(report), datetime 타입 수정**

CREATE TABLE report (
report_id bigint not null AUTO_INCREMENT,
user_id bigint not null,
college_id bigint not null,
car_number varchar(255) not null,
cause varchar(255) not null,
report_date datetime not null,
reprot_result varchar(255) not null,
constraint reports_PK primary key(report_id),
FOREIGN KEY (user_id) REFERENCES user (user_id),
FOREIGN KEY (college_id) REFERENCES college (college_id)
);

![image](https://user-images.githubusercontent.com/87069221/177925461-5a6a49c0-a5bc-46e3-b2c6-a2f34a1e1873.png)
