### ISSUE TITLE
7.9 전달사항 <FCM Android 확인 바람>

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#54]
# 7.3일에 구현 성공한 알림 기능

### 서버 -> firebase 서버 -> App

<br/>

단점

* Web에서 호출 불가능
* 비동기가 아님
* 단일 송신임

<br/>

---

<br/>

# 7.9일에 시도 중인 알림 기능

![1, 기존 API 사용해야함](https://user-images.githubusercontent.com/76596316/178105488-57a8e2ed-65a9-411d-a41b-373bdcdf42ed.png)

* Firebase Cloud Messaging API(V1)가 아닌 Cloud Messaging API(기존) 사용해서 구현

<br/><br/>

### web view -> 서버 -> firebase 서버 -> App

<br/>

장점

* Web에서 호출 가능
* 비동기 통신 (@Async, 자바 8 API CompletableFuture 사용)
* 다중 송신 가능

<br/>

# 결론

### 링크 2개 들어가서 동일하게 Android 셋팅한 후, Web 이랑 테스트

<br/>

* 중복되는 부분은 알아서 슥슥 넘어가면서 설정하면 됨

<br/>

[Firebase project 생성](https://medium.com/2kyung19/firebase-project-%EC%83%9D%EC%84%B1-7ffd94217f66)

* 확인하면서 안 맞는 거 있나 점검

<br/>

[Firebase, Android 연동 및 push 알림 보내기](https://medium.com/2kyung19/firebase-android-%EC%97%B0%EB%8F%99-%EB%B0%8F-push-%EC%95%8C%EB%A6%BC%EB%B3%B4%EB%82%B4%EA%B8%B0-ec6c57b2eb68)

* 확인하면서 구현

<br/><br/>

* 프로젝트명 test 사용

**Comment by khg339** [comment]
![사라짐](https://user-images.githubusercontent.com/87069221/178311095-dd582681-0d05-49a0-ad37-97bbf5ec6ad2.PNG)
![오류2](https://user-images.githubusercontent.com/87069221/178311104-a811f6a8-929d-44cf-8ea7-2a41e3ebad6c.PNG)

2019년도 글이라 없어진 클래스 및 함수가 있음 -> 다른 메소드로 수정함
알림 푸시 적용되는거 확인함(+ 토큰 값 띄우기)
