### ISSUE TITLE
7.31일 (일요일) 회의 오후 5시 & 숙제

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#57]
# 7.31일 (일요일) 회의 오후 5시

<br/>

### Web/App 기능 구현

**Comment by HongJungWan** [comment]
# 7.25일 App DB에 맞춰 수정한 Web DB

![7 25 web DB](https://user-images.githubusercontent.com/76596316/180714782-2863d694-0395-4ef6-b8d8-663cef3b0e3b.png)

### 초록색 : 무슨 역할인지 궁금

### 빨간색 : 추가 바람

**Comment by khg339** [comment]
**7월 25일 회원 신고 1차 구현**

![신고](https://user-images.githubusercontent.com/87069221/180758139-5372fb92-604e-4744-933e-3ac1b609246d.PNG)

![신고db](https://user-images.githubusercontent.com/87069221/180758093-423cffcc-4643-4e3c-8278-16d664933b54.PNG)
832e0.PNG)

**Comment by HongJungWan** [comment]
![대충 만든거 7 25](https://user-images.githubusercontent.com/76596316/180772926-1c0d97a8-202d-403b-b5b6-a434c3bb58cd.png)

내부적으로 돌아가는 서버 코드 대충만들어서 수정하면 될듯

**Comment by HongJungWan** [comment]
Dto로 넘겨서 엔티티 노출 안 되게 바꿨고,

App DB에 맞춰서 수정한 DB RDS에 마이그레이션 했는데 

~~1. 주차장 등록~~
~~2. 예약~~
~~3. 기타 등등 css~~
~~4. Test 오류~~

~~등 트러블 슈팅 발생~~

~~이번 주에 DB에 맞춰서 고쳐볼 예정~~

전부 해결
