### ISSUE TITLE
자료 수집 1차

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#6]
## 주제 : 번호판 인식을 통한 [???] 웹페이지

숙제 : 관련 자료 찾기

<br/>

 ----

<br/>

개발과정

개발기간
1학기 :
2학기 :

역할

**Comment by HongJungWan** [comment]
무료 주차 요금 정산기 앱
https://play.google.com/store/apps/details?id=com.mobilelpr

무료 주차 요금 웹서비스
http://mparking.securitynmap.com/view/main.aspx

---

보통 차량 번호판 인식 기능 구현까지만 하고 이걸로 서비스를 하는 경우는 별로 없다.

크게 2가지로 나뉜다.

1. 주차 단속
2. 주차 요금 

결론 : 둘 다 웹까지 구현한 오픈소스는 공모전 및 깃허브에서 찾지 못했다. 

<br/>

아마 최대 결과물은
"딥러닝 기반 주차 구역 관리 웹서비스"

<br/>

같은 결과물이라도 제목에 따라 입상이냐 아니냐 나뉠듯하다.

**Comment by pennya6** [comment]
관련 자료는 정확하게 번호판인식과 웹서비스를 도입한 서비스를 찾을 수 없다. 
대부분은 번호판 인식까지의 방법에 대해서 서술하고 있다.
   
그나마 비슷한 서비스로는 저번에 이야기한 주차장 관리지기앱이다. 하지만 이도 가게앞이나 자투리땅을 주차장으로 관리한다는 점에서 과거에 이슈된 소재로 트렌드하지 못하며 약간 다르다.
https://m.blog.naver.com/PostView.naver?blogId=beodeulpiri&logNo=221719960335&proxyReferer=https:%2F%2Fm.blog.naver.com%2FPostView.naver%3FblogId%3Dbeodeulpiri%26logNo%3D222045064295%26proxyReferer%3Dhttps:%252F%252Fwww.google.com%252F

따라서 번호판 인식 웹서비스에 대한 아이디어를 더욱 상세하게 제안하고자 한다.

[우리 주제의 핵심 기능]

1. 번호판 인식
2. 웹서비스

현재 주차요금 정산, 관리 시스템은 보편적으로 많이 사용되고 있는 소재이다.
따라서 두가지 핵심기능을 활용한 다른 주제를 고려하였을때
+ <strong>택시 번호 조회</strong> 
-> 택시 분실물, 택시운전자 및 택시회사 관련 조회 가능, 택시 요금 예측 등 다양한 택시 이용자들을 위한 웹서비스를 구축
이는 솔직히 안드로이드로 구축하는게 최적화되어 있다고 생각한다.

아니면 우리 학교에 최적화된 웹서비스를 구축
+ <strong>한신대학교 주차관리시스템</strong>
-> 현재 한신대학교에서는 정기권 차량번호 등록 및 신청을 통해 관리하고 있다.  
![image](https://user-images.githubusercontent.com/53909511/155073286-d27b2c33-cf7e-496a-bbb6-a2d99931b1d5.png)
관련 서비스들을 웹으로 관리할 수 있게 서비스 제공하여 사용자들이 직접 주관부서를 방문해야하는 불편을 없애고자 한다.
위의 서비스를 구축한다고 하면 시간을 더 투자하여 서비스배포까지 가면 좋을 듯 하다. 
실질적으로 사용가능할 수 있음을 어필하면 좋을 듯 하다.

**Comment by khg339** [comment]
지금 시연이가 올려준 부분들이 제가 정리하고 있었던 부분들이에요


1. 택시 or 버스 분실물 소재
분실물이 생길지도 모르니까 타기 전에 매번 번호판을 찍고 탑승하는 경우가 일반적이지 않다고 생각이 들었다.
그리고 대부분 카카오 택시나 카드 결제를 하면 차량 번호를 알 수 있다고 한다.


2. 우리 학교를 기반으로 발전
학사 졸업논문에서 '독창성'이 아니라 '창의성' 을 보는 것이라고 한다.
주차 관리 시스템을 저희 학교 주차 시스템을 발전시키는 방향으로 해도 구현이 중요한 거라서 괜찮을 것 같다.


------------------------------------------------------------------------------


<한신 대학교 주차권 사용 과정>
(주차료(학기권/월권) 국민은행 납입 → 대학원교학팀 방문 → 입금증 및 납입 확인 → 정기주차 등록/변경신청서 작성 → 정문 경비실 제출 → 등록)

=> 과정이 귀찮고 복잡함 -> 무인 시스템으로 도입


------------------------------------------------------------------------------

https://www.boannews.com/media/view.asp?idx=96509
가짜 번호판도 차량 번호로 인식함(ex 종이에 적은 번호도 차량 번호로 인식함)

따라서 부가적인 인증 시스템이 필요할 것 같음
(마트에서 장보면 영수증 인증이나, 아파트의 호수 입력과 같은)

**Comment by pennya6** [comment]
[현지 아이디어에 대한 의견]
1. 택시 or 버스 분실물 소재
-> 사용자가 택시나 버스 번호판을 찍는 일은 거의 없을 것 같다. 그러면 초기 택시운전자가 번호판인식을 통한 등록은? 
굳이 번호판인식으로 등록을 해야하는가에 대한 의문이 생길 수 있다.  이는 번호판 색상, '아바자사'(상업용이라는 의미), 등록되어있는 번호판인가 등의 여부를 자동적으로 조회할 수 있다면? 이는 DB에서 처리할 수 있지 않을까?

2.  학교 홈페이지에 적용한 소재
-> 창의성이 있는건가? 의문이 든다..... 다른 학교 예시도 조사해보자
+ 경기대학교 
![image](https://user-images.githubusercontent.com/53909511/155103809-9dd748ce-d956-4487-a579-8a43927dddb5.png)

+ 아주대학교
![image](https://user-images.githubusercontent.com/53909511/155104029-ef799228-0ddf-4f3c-b39b-b28364b89f8e.png)

+ 성균관대학교 
![image](https://user-images.githubusercontent.com/53909511/155104304-5396e9a3-10e8-4dcd-89ff-b5cbd98ac412.png)

결론적으로 보았을때 신규든지 차량을 교체했을 경우에 방문이 필요하다. 즉 방문없이 웹페이지를 통해 신청할 수 있는 학교는 위의 3군데중 없음

**Comment by khg339** [comment]
여기서 또 갑자기 처음으로 돌아가는 것 같은 의문이 생겼는데..

웹페이지를 통해 신청을 하게 될 때,
차량 번호를 직접 입력할 수 있음에도 불구하고, 이미지를 업로드 하는 이유가 무엇일까..?

성균관대학교도 어플을 이용하여 신청하는 방식이 있음
-> 자동차 등록증, 등본 등 공문 서류를 통해 승인함(번호판 확인X)
