### ISSUE TITLE
[회의 X] 8.20일 까지 [Web], [App] I.A 올려주세요.

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#66]
Issue에 올려주세요

**Comment by HongJungWan** [comment]
# [Web] I.A(Information Architecture)

[Web IA 22-08-18.pdf](https://github.com/Capstone-Demo/Re-Coder-App-Web/files/9366975/IA.22-08-18.pdf)

**Comment by khg339** [comment]
<h1> [App] I.A(Information Architecture)</h1>

[Android_IA_22-08-20.pdf](https://github.com/Capstone-Demo/Re-Coder-App-Web/files/9386699/Android_IA.pdf)
