### ISSUE TITLE
자료 정리 2차

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#7]
## 주제 : "딥러닝 기반 주차 구역 관리 웹서비스"

</br>

안드로이드(카메라) -> 영상처리, 딥러닝 -> 웹사이트

</br></br>

1학기 목표 목표 : 안드로이드(카메라) -> 영상처리, 딥러닝

</br>

1학기 주요 학습 주제 : 안드로이드, 영상처리, 딥러닝 

</br>

--------------------------------------------------------------

딥러닝( CNN -> 차량 번호판 인식) 

컴퓨터 비전 (객체 인식)  

</br>
주요 학습 주제랑 매칭되는 자료 및 사이트 링크로 올려주세요.

**Comment by HongJungWan** [comment]
무료 강의(인프런, 유튜브)는 학부 강의 수준 -> 실제로 프로젝트로 구현까지는 힘들어 보인다.
(cs 블로그) 간단한 이론만 다룬다.

---

딥러닝 CNN 완벽 가이드
<a href ="https://www.inflearn.com/course/%EB%94%A5%EB%9F%AC%EB%8B%9D-cnn-%EC%99%84%EB%B2%BD-%EA%B8%B0%EC%B4%88">링크1</a>

</br>

차량 번호판 인식 프로젝트와 TensorFlow로 배우는 딥러닝 영상인식 올인원 ★
<a href ="https://www.inflearn.com/course/tensorflow-%EC%8B%A4%EC%A0%84%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EC%98%AC%EC%9D%B8%EC%9B%90">링크2</a>

---

토요일에 링크 2 보다 더 좋은 학습자료 없으면 결제할 계획

**Comment by pennya6** [comment]
1. Tesseract을 사용하여 정화도를 높이는가 혹은 딥러닝 모델을 구현할 것 인가 를 선택해야할듯
2. 안드로이드 tesseract ocr sample code - https://junyoung-jamong.github.io/computer/vision/2019/02/07/Android-Tesseract-사용하기.html
3. 간단하게 다들 시도해보면 좋을 듯 한 code - https://blog.naver.com/PostView.naver?blogId=khcapfhd&logNo=221720447928
4. 러닝스푼지 컴퓨터비전 딥러닝 강의 id (개인정보 지움) : , pw : (개인정보 지움)
튕길수도 있으니 들을때 톡하기
https://learningspoons.com/
5. 우리는 객체 검출이 아니라 텍스트 추출쪽 따라서 ocr를 어떤 알고리즘을 선택하냐의 문제일것 같다. Opencv는 텍스트가 있는 localization까지 하고 추후에 ocr 사용 이런식으로 고려해야한다.
6. 전체적으로 같이 학습을 하되 1명은 안드로이드 test을 진행하고 있으면 좋을 듯 하다.

**Comment by HongJungWan** [comment]
<a href ="https://stackshare.io/stackups/opencv-vs-tesseract-ocr">OpenCV vs Tesseract OCR</a>

---

### 회의 때 나눠볼 질문

<br/>

1. Opencv 랑 ocr 둘 다 하는 이유가 인식률 차이 비교해 보려고 하는 건가?

<br/>

2. 정확도 높인다. -> OpenCV가 유리하다. </br>모델 구축한다. -> Tesseract OCR가 유리하다.

**Comment by HongJungWan** [comment]
개인 정보 있어서 숨김

**Comment by HongJungWan** [comment]
1. Tesseract을 사용하여 정확도를 높이자 ★


2. 딥러닝 모델을 구현할 것 인가 를 선택해야할듯

----

## 숙제

1. 안드로이드 tesseract ocr sample code - [https://junyoung-jamong.github.io/computer/vision/2019/02/07/Android-Tesseract-사용하기.html](https://junyoung-jamong.github.io/computer/vision/2019/02/07/Android-Tesseract-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0.html), (3월 8일까지)

<br/>

2. 러닝스푼지 컴퓨터비전 딥러닝 강의, (18시간, 목차라도 보고오기)

1강 && 객체 탐지 뽑아 듣기
