### ISSUE TITLE
a problem occurred configuring project ':app'. > java.lang.nullpointerexception (no error message) 오류 발생 시

### ISSUE THREAD

**Issue by HongJungWan** [Capstone-Demo/Capstone-Demo#9]
### a problem occurred configuring project ':app'. > java.lang.nullpointerexception (no error message) 
오류 발생 시
---

<br/>

빌드 오류 or ndk 오류
고질적인 안드로이드 스튜디오 오류로 보임.

[오류 해결](https://velog.io/@daydream/Android-Studio-No-toolchains-found-in-the-NDK-toolchains-folder-for-ABI-with-prefix-arm-linux-androideabi-%EC%98%A4%EB%A5%98)

<br/>

---

기존 예제 코드 안 돌아갈 시,
[Android NDK + CMake + OpenCV 카메라 예제 및 프로젝트 생성 방법](https://webnautes.tistory.com/1054)

<br/>

---

<br/>

깃허브에 있는 대다수 오픈소스 호환 안되거나 모바일에 직접 연결해서 동작시켰을 때 앱 죽음
다른 해결 방법 있다면 이슈 올려주길 바람

[MNIST 손글씨 숫자 인식](https://github.com/webnautes/Tensorflow_Lite_Example)

이런 건 똑같이 NDK 오류인데 잘 돌아감

**Comment by HongJungWan** [comment]
branch 코드는 깨진 상태 -> 원하시면 다시 올려드림

**Comment by khg339** [comment]
안드로이드 자체에 오류가 많아서 대부분 잘 안될 때 이것들 한 번씩 하는 게 좋다고 해요
https://kim-hoya.tistory.com/45

symbol오류 말고도 이유 없이 빨간 글씨 뜰 때 대부분 해결 된다고 합니다
